### ISSUE TITLE
Download YAML file too

### ISSUE THREAD

**Issue by nicholasamorim** [ikalnytskyi/sphinxcontrib-redoc#22]
Hi and first of all: thanks for this amazing project!

I was wondering if there could be an option for downloading the API spec in YAML too. The download button retrieves only a JSON version.

My use case is that we as an organisation actually works with the YAML versions as they are easier on the eyes and easier for non-tech people to look at and/or edit.

**Comment by ikalnytskyi** [comment]
Hey @nicholasamorim! I wonder, what's your setup and how you use this plugin? ReDoc's *download* button downloads whatever's linked under the hood. If you initially passed YAML, the YAML will be downloaded.

The only thing that comes to my mind is that, don't you use `embed` feature along with YAML specs? Because if `embed ` feature is used, the spec will be converted to JSON internally. And thus, the JSON will be downloaded instead.

**Comment by nicholasamorim** [comment]
This is basically how I use it on `conf.py`

```python
```

**Comment by nicholasamorim** [comment]
Right, I'm using `embed` indeed. I thought this was side-effect free as in: it will embed on the page but I'll still download the original file.

Thanks for answering!

**Comment by annetre** [comment]
Unfortunately, deleting `embed` or setting it to False causes an error. I'm using 2.1.3 version
![image](https://github.com/sphinx-contrib/redoc/assets/112639217/34174a32-11c7-4000-a985-f5691e5d6e02)


What changes should I do to download YAML instead of JSON file? 
Thanks in advance.
